# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Taking a long view
email: blamestross@gmail.com
description: >
  Explaination and Discussion of an unrepresented worldview
logo: "assets/images/avatar.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blamestross.github.io" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'Brendan Benshoof'
bio: >
  I am a computer science PhD canidate at Georgia State University.
  My research has focused on building decentralized and robust p2p networking systems.
  This blog is a platform for disscussing the application of the philosphy of my research to the organization of human society.
author_image: "assets/images/avatar.jpg"

github_username: "brendanbenshoof"

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
